module.exports = {
    MAX_RANK_POINTS_ON_LOSE : -4,
    MAX_RANK_POINTS_ON_WIN  : 4,
    LEVEL_POINTS_ON_LOSE : 50,
    LEVEL_POINTS_ON_DRAW : 100,
    LEVEL_POINTS_ON_WIN  : 200,
    SERVER_PORT: 3000,
};